project:
  type: website

website:
  title: "Swayam's Scripts"
  open-graph: true
  favicon: favicon.png
  page-footer: Â© 2025 Swayam Singh. All rights reserved.
  navbar:
    right:
      - icon: house-fill
        href: https://swayaminsync.github.io/
      - icon: github
        href: https://github.com/SwayamInSync
      - icon: twitter
        href: https://x.com/swayaminsync
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    include-after-body: ongoing-toggle.html
